{
 "title": "Intelligent Mask",
 "time": { "from": "2021-06-15T15:16:16.000Z", "to": "2021-06-15T15:27:42.000Z" },
 "panels": [
  {
   "title": "Current body temperature",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature\nFROM dynamo_test\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Body temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature\nFROM dynamo_test\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Heart rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "bpm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  t_lambda AS \"time\",\n  heartrate\nFROM dynamo_usiing_fromlambda\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure level",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stress\nFROM dynamo_stress\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blood oxygen",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  oxygenconc\nFROM dynamo_test\nORDER BY 1"
    }
   ]
  }
 ]
}